### ISSUE TITLE
Slash behind a file names too.

### ISSUE THREAD

**Issue by aadrian** [takezoe/gitbucket-maven-repository-plugin#12] opened 2019-02-07 16:42 UTC
The current version - https://plugins.gitbucket-community.org/releases/gitbucket-maven-repository-plugin/gitbucket-maven-repository-plugin-gitbucket_4.30.1-1.4.0.jar  renders slashes behind file names too, not just directories, so it's very confusing what is a file name and what's a directory. 

Thank you.

**Comment by ziggystar** [comment] 2019-07-24 10:08
In addition it results in the file name being empty when downloading via browser. Apparently IE has a "bug", and there it works.

**Comment by GabrieleFrau** [comment] 2021-08-12 15:05
This might be the cause
https://github.com/takezoe/gitbucket-maven-repository-plugin/blob/f817f7130a3482fe9dfedaf59fd39ec8070c2d85/src/main/twirl/gitbucket/mavenrepository/files.scala.html#L46-L50

**Comment by takezoe** [comment] 2021-08-31 05:44
Oh, that should be fixed!

**Closed as completed** 2021-09-05 05:21 UTC
Labels: bug
